//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArchiveApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArchiveApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Root&gt;
        ///  &lt;Units id=&quot;1&quot; name=&quot;natio&quot;&gt;
        ///    &lt;Item  key=&quot;0&quot; value=&quot;Русский&quot;/&gt;
        ///    &lt;Item  key=&quot;1&quot; value=&quot;Украинец&quot;/&gt;
        ///    &lt;Item  key=&quot;2&quot; value=&quot;Беларус&quot;/&gt;
        ///    &lt;Item  key=&quot;3&quot; value=&quot;Узбек&quot;/&gt;
        ///    &lt;Item  key=&quot;4&quot; value=&quot;Татжик&quot;/&gt;
        ///    &lt;Item  key=&quot;5&quot; value=&quot;Казах&quot;/&gt;
        ///    &lt;Item  key=&quot;6&quot; value=&quot;Якут&quot;/&gt;
        ///    &lt;Item  key=&quot;7&quot; value=&quot;Азербайджанец&quot;/&gt;
        ///    &lt;Item  key=&quot;8&quot; value=&quot;Латыш&quot;/&gt;
        ///    &lt;Item  key=&quot;9&quot; value=&quot;Поляк&quot;/&gt;
        ///    &lt;Item  key=&quot;10&quot; value=&quot;Кавказец&quot;/&gt;
        ///  &lt;/Units&gt;
        ///  
        ///   [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string DropDownData {
            get {
                return ResourceManager.GetString("DropDownData", resourceCulture);
            }
        }
    }
}
