USE [ArchiveDb]
GO

--SET IDENTITY_INSERT [Layners] ON;
INSERT INTO [Natio] VALUES(N'Русский') 
INSERT INTO [Natio] VALUES(N'Украинец')
INSERT INTO [Natio] VALUES(N'Казах')
INSERT INTO [Natio] VALUES(N'Беларус') 
INSERT INTO [Natio] VALUES(N'Кавказец')
INSERT INTO [Natio] VALUES(N'Азербайджанец')
INSERT INTO [Natio] VALUES(N'Поляк')
INSERT INTO [Natio] VALUES(N'Латыш')
INSERT INTO [Natio] VALUES(N'Узбек')
INSERT INTO [Natio] VALUES(N'Татжик')
INSERT INTO [Natio] VALUES(N'Якут')
INSERT INTO [Natio] VALUES(N'Болгар')
INSERT INTO [Natio] VALUES(N'Удмурт')
INSERT INTO [Natio] VALUES(N'Татар')
INSERT INTO [Natio] VALUES(N'Башкир')
INSERT INTO [Natio] VALUES(N'Чуваш')
INSERT INTO [Natio] VALUES(N'Чеченец')
INSERT INTO [Natio] VALUES(N'Аварец')
INSERT INTO [Natio] VALUES(N'Мордовец')
INSERT INTO [Natio] VALUES(N'Даггестанец')
INSERT INTO [Natio] VALUES(N'Осетинец')
INSERT INTO [Natio] VALUES(N'Кабардинец')
INSERT INTO [Natio] VALUES(N'Кумык')
INSERT INTO [Natio] VALUES(N'Бурят')
INSERT INTO [Natio] VALUES(N'Ингуш')
INSERT INTO [Natio] VALUES(N'Коми')
INSERT INTO [Natio] VALUES(N'Цыган')
INSERT INTO [Natio] VALUES(N'Калмык')
INSERT INTO [Natio] VALUES(N'Еврей')
INSERT INTO [Natio] VALUES(N'Молдован')
INSERT INTO [Natio] VALUES(N'Кореец')
INSERT INTO [Natio] VALUES(N'Армян')
INSERT INTO [Natio] VALUES(N'Адыгеец')
INSERT INTO [Natio] VALUES(N'Киргиз')
INSERT INTO [Natio] VALUES(N'Ненец')
INSERT INTO [Natio] VALUES(N'Туркмен')
INSERT INTO [Natio] VALUES(N'Китаец')
INSERT INTO [Natio] VALUES(N'Эстонец')
INSERT INTO [Natio] VALUES(N'Вьетнамец')
INSERT INTO [Natio] VALUES(N'Абхаз')
INSERT INTO [Natio] VALUES(N'Араб')
INSERT INTO [Natio] VALUES(N'Монгол')
INSERT INTO [Natio] VALUES(N'Крымский татар')
INSERT INTO [Natio] VALUES(N'Черкес')

INSERT INTO [Education] VALUES(N'Нет образования') 
INSERT INTO [Education] VALUES(N'Среднее')
INSERT INTO [Education] VALUES(N'Средне-специальное')
INSERT INTO [Education] VALUES(N'Высшее')

INSERT INTO [Party] VALUES(N'Беспартийный') 
INSERT INTO [Party] VALUES(N'Член партии')
INSERT INTO [Party] VALUES(N'Комсомол')

INSERT INTO [FamilyType] VALUES(N'Женат') 
INSERT INTO [FamilyType] VALUES(N'Замужем')
INSERT INTO [FamilyType] VALUES(N'Разведен(-а)')
INSERT INTO [FamilyType] VALUES(N'Вдовец(-ва)')

INSERT INTO [Social] VALUES(N'Крестьянин') 
INSERT INTO [Social] VALUES(N'Рабочий')
INSERT INTO [Social] VALUES(N'Служащий')

INSERT INTO [Organ] VALUES(N'Судебная коллегия ОГПУ')
INSERT INTO [Organ] VALUES(N'Особое Совещание при НКВД')
INSERT INTO [Organ] VALUES(N'Тройки УНКВД')
INSERT INTO [Organ] VALUES(N'Тройки при ПП ОГПУ в Казахстане')
INSERT INTO [Organ] VALUES(N'Особая тройка')
INSERT INTO [Organ] VALUES(N'Протоколы НКВД и прокурора СССР')
INSERT INTO [Organ] VALUES(N'Большая тройка НКВД и Прокуратура СССР')
INSERT INTO [Organ] VALUES(N'Выездная сессии ПП ОГПУ в Казахстане')
INSERT INTO [Organ] VALUES(N'Другое')

INSERT INTO [Updates] VALUES(0)
	